version:     "00014--14-May-2022"
copyright:   "2022"
author:      "Anne Yuliana"
title:       "OS221: Operating Systems 2022-1"
githublink:  "https://github.com/annesafrina/os221/"
myloglink:   "TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
